[package]
name = "chomp"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
rusqlite = { version = "0.32.1", features = ["bundled", "chrono"] }
serde_json = "1.0"
serde = "1.0"
chrono = "0.4.39"
